# Generated by Django 6.0.7 on 2026-07-27 18:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=50)),
                ('Item_Category', models.CharField(choices=[('Special Items', 'Special Items'), ('Tandoori Items', 'Tandoori Items'), ('Non Veg Snacks', 'Non Veg Snacks'), ('Non Veg Main Course', 'Non Veg Main Course'), ('Kebab', 'Kebab'), ('Fish Special', 'Fish Special'), ('Veg Snacks', 'Veg Snacks'), ('Veg Main Course', 'Veg Main Course'), ('Roti / Prantha', 'Roti / Prantha'), ('Pasta', 'Pasta'), ('Beverages', 'Beverages'), ('Salad', 'Salad')], max_length=50)),
                ('Item_size', models.CharField(choices=[('Half', 'half'), ('Full', 'full')], max_length=10)),
                ('Item_Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
