# Generated by Django 6.0.7 on 2026-07-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='Item_size',
            new_name='Item_Size',
        ),
    ]
