# Generated by Django 6.0.7 on 2026-07-27 18:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Details', '0001_initial'),
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Cust_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Table_No', models.PositiveBigIntegerField(blank=True, null=True)),
                ('Car_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('Source', models.CharField(choices=[('Customer', 'customer'), ('Owner', 'owner'), ('Staff', 'staff')], max_length=20)),
                ('Payment_Status', models.CharField(blank=True, max_length=10, null=True)),
                ('Status', models.CharField(choices=[('Preparing', 'preparing'), ('Accepted', 'accepted'), ('Ready To Collect', 'ready to collect'), ('Delivered', 'delivered')], default='pending', max_length=20)),
                ('Payment_Type', models.CharField(blank=True, choices=[('Online', 'online'), ('Offline', 'offline')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Staff_Assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order', to='Details.details')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('order_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order_Items', to='Menu.menu')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Items', to='Order.order')),
            ],
        ),
    ]
