# Generated by Django 6.0.7 on 2026-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Bill_Printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
